pull_request_rules:
- name: Automatic approval for Renovate pull requests
  conditions:
  - author=renovate[bot]
  actions:
    review:
      type: APPROVE
      message: Automatically approving renovate
